package test_app.models;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 * 
 * @author Dreads
 *
 */
@Entity
@Table(name = "buildings")
public class Building {
	
	// An autogenerated id (unique for each room in the db)
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private long id;
	
	@NotNull
	private String buildingName;
	
	@NotNull
	private int noFloors;
	
	public Building() {}
	
	public Building(long id){
		this.id = id;
	}

	public Building(long id, String buildingName, int noFloors){
		this.id = id;
		this.buildingName = buildingName;
		this.noFloors = noFloors;
	}
	public long getId(){
		return this.id;
	}
	public void setId(long id){
		this.id = id;
	}
	public String getBuildingName(){
		return this.buildingName;
	}
	public void setBuildingName(String buildingName){
		this.buildingName = buildingName;
	}
	public int getNoFloors(){
		return this.noFloors;
	}
	public void setNoFloors(int noFloors){
		this.noFloors = noFloors;
	}
}
