package test_app.models;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

@Entity
@Table(name = "event_sign_ups")
public class EventSignUp {
	
	// An autogenerated id (unique for each room in the db)
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private long id;
	
	@NotNull
	private long eventId;
	
	@NotNull
	private String username;
	
	public EventSignUp(){}
	
	public EventSignUp(long eventId){
		this.eventId = eventId;
	}
	
	public EventSignUp(long eventId, String username){
		this.eventId = eventId;
		this.username = username;
	}
	
	public long getId(){
		return this.id;
	}
	public void setId(long id){
		this.id = id;
	}
	
	public long getEventId(){
		return this.eventId;
	}
	public void setEventId(long eventId){
		this.eventId = eventId;
	}
	public String getUsername(){
		return this.username;
	}
	public void setUsername(String username){
		this.username = username;
	}
}
