package test_app.models;


import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

@Entity 
@Table(name = "user_pictures")
public class UserPicture {
	
	// An autogenerated id (unique for each user in the db)
	@Id
    @GeneratedValue(strategy = GenerationType.AUTO)
	private long id;
	  
	@NotNull
	private String username;

	private String imageString;

	public UserPicture(){ }

	public UserPicture(String username, String imageString){
		this.username = username;
		this.imageString = imageString;
	}
	public UserPicture(long id, String username, String imageString){
		this.id = id;
		this.username = username;
		this.imageString = imageString;
	}
	public long getId(){
		return this.id;
	}
	public void setId(long id){
		this.id = id;
	}
	
	public String getUsername(){
		return this.username;
	}
	public void setUsername(String username){
		this.username = username;
	}
	public String getImageString(){
		return this.imageString;
	}
	public void setImageString(String imageString){
		this.imageString = imageString;
	}
}
