package test_app.models;


import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

@Entity 
@Table(name = "users")
public class User {
	
	// An autogenerated id (unique for each user in the db)
	  @Id
	  @GeneratedValue(strategy = GenerationType.AUTO)
	  private long id;
	  
	  @NotNull
	  private String username;
	  
	  @NotNull 
	  private String password;
	  
	  @NotNull
	  private String salt;
	  
	  @NotNull
	  private String email;
	  
	  @NotNull
	  private String matricNo;
	  private String firstName;
	  private String lastName;
	  private String accountType;
	  
	  
	  // Public methods
	  
	  public User() { }

	  public User(long id) { 
	    this.id = id;
	  }
	  
	  public User(String firstName, String password) {
	    this.firstName = firstName;
	    this.password = password;
	  }
	  public User(String username, String password, String salt, String email, String matricNo, String firstName, String lastName, String accountType){
		  this.username = username;
		  this.password = password;
		  this.salt = salt;
		  this.email = email;
		  this.matricNo = matricNo;
		  this.firstName = firstName;
		  this.lastName = lastName;
		  this.accountType = accountType;
	  }
	  

	  // Getter and setter methods
	  // ...
	  
	  /**
	   * 
	   * @return id
	   */
	  public long getId(){
		  return this.id;
	  }
	  /**
	   * 
	   * @param id
	   */
	  public void setId(long id){
		  this.id = id;
	  }
	  /**
	   * 
	   * @return username
	   */
	  public String getUserName(){
		  return this.username;
	  }
	  /**
	   * 
	   * @param username
	   */
	  public void setUserName(String username){
		  this.username = username;
	  }
	  /**
	   * 
	   * @return password
	   */
	  public String getPassword(){
		  return this.password;
	  }
	  /**
	   * 
	   * @param password
	   */
	  public void setPassword(String password){
		  this.password = password;
	  }
	  
	  
	  public String getSalt(){
		  return this.salt;
	  }
	  public void setSalt(String salt){
		  this.salt = salt;
	  }
	  /**
	   * 
	   * @return email
	   */
	  public String getEmail(){
		  return this.email;
	  }
	  /**
	   * 
	   * @param email
	   */
	  public void setEmail(String email){
		  this.email = email;
	  }
	  
	 
	  /**
	   * 
	   * @return matricNo
	   */
	  public String getMatricNo(){
		  return this.matricNo;
	  }
	  /**
	   * 
	   * @param matricNo
	   */
	  public void setMatricNo(String matricNo){
		  this.matricNo = matricNo;
	  }
	  
	  
	  
	  /**
	   * 
	   * @return firstName
	   */
	  public String getFirstName(){
		  return this.firstName;
	  }
	  /**
	   * 
	   * @param firstName
	   */
	  public void setFirstName(String firstName){
		  this.firstName = firstName;
	  }
	  
	  /**
	   * 
	   * @return lastName
	   */
	  public String getLastName(){
		  return this.lastName;
	  }
	  /**
	   * 
	   * @param lastName
	   */
	  public void setLastName(String lastName){
		  this.lastName = lastName;
	  }
	  /**
	   * 
	   * @return accountType
	   */
	  public String getAccountType(){
		  return this.accountType;
	  }
	  /**
	   * 
	   * @param accountType
	   */
	  public void setAccountType(String accountType){
		  this.accountType = accountType;
	  }
}
